name: CI/CD with uv Demo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: "~/.cache/uv"
          key: uv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run tests with pytest
        run: uv run --with pytest python -m pytest -v
