name: CI/CD with uv Demo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: "~/.cache/uv"
          key: uv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Run tests with pytest
        run: uv run --with-requirements requirements.txt python -m pytest -v

      - name: Demonstrate uv speed (alternative approach)
        if: failure()
        run: |
          echo "Demonstrating uv's pip functionality:"
          uv pip install pytest rich
          uv run pytest -v
